Replace spaces with tabs.

diff --git a/pi-backup b/pi-backup
--- a/pi-backup
+++ b/pi-backup
@@ -31,8 +31,8 @@ DEST=$SSH_USER@$ADDRESS:$DEST_DIR
 
 if (! $SSH_COMMAND $SSH_USER@$ADDRESS "[ -d $DEST_DIR ]")
 then
-  echo "Backup destination does not exist. Abort."
-  exit 1
+	echo "Backup destination does not exist. Abort."
+	exit 1
 fi
 
 for directory in ${DIRECTORIES[@]}
